export const NOI_DUNG = [
  {
      id: 1000,
      tenDm: "Lương thực",
      idCha: 0,
      level: 0,
  },
  {
      id: 1100,
      tenDm: "Phát sinh trong kỳ",
      idCha: 1000,
      level: 1,
  },
  {
      id: 1110,
      tenDm: "Thóc",
      idCha: 1100,
      level: 2,
  },
  {
      id: 1120,
      tenDm: "Gạo",
      idCha: 1100,
      level: 2,
  },
  {
      id: 1121,
      tenDm: "Thay đổi kỹ thuật (chi tiết theo từng đề xuất cụ thể)",
      idCha: 1120,
      level: 3,
  },
  {
      id: 1122,
      tenDm: "Thực hiện cắt giảm dự toán để đảm bảo mục tiêu cân đối NSNN theo quyết định của cơ quan có thẩm quyền",
      idCha: 1120,
      level: 3,
  },
  {
      id: 1200,
      tenDm: "Lũy kế từ đầu năm",
      idCha: 1000,
      level: 1,
  },
  {
      id: 1210,
      tenDm: "Thóc",
      idCha: 1200,
      level: 2,
  },
  {
      id: 1220,
      tenDm: "Gạo",
      idCha: 1200,
      level: 2,
  },
  {
      id: 2000,
      tenDm: "Vật tư, hàng hóa khác",
      idCha: 0,
      level: 0,
  },
  {
      id: 2100,
      tenDm: "Phát sinh trong kỳ",
      idCha: 2000,
      level: 1,
  },
  {
      id: 2110,
      tenDm: "Phao bè",
      idCha: 2100,
      level: 2,
  },
  {
      id: 2120,
      tenDm: "Xuồng DT1",
      idCha: 2100,
      level: 2,
  },
  {
      id: 2121,
      tenDm: "Thay đổi kỹ thuật (chi tiết theo từng đề xuất cụ thể)",
      idCha: 2120,
      level: 3,
  },
  {
      id: 2122,
      tenDm: "Thực hiện cắt giảm dự toán để đảm bảo mục tiêu cân đối NSNN theo quyết định của cơ quan có thẩm quyền",
      idCha: 2120,
      level: 3,
  },
  {
      id: 2200,
      tenDm: "Lũy kế từ đầu năm",
      idCha: 2000,
      level: 1,
  },
  {
      id: 2210,
      tenDm: "Phao bè",
      idCha: 2200,
      level: 2,
  },
  {
      id: 2220,
      tenDm: "Xuồng DT1",
      idCha: 2200,
      level: 2,
  },
  {
      id: 2230,
      tenDm: "Máy phát điện",
      idCha: 2200,
      level: 2,
  },
]
