export const PHU_LUC = [
    {
        id: 'pl01',
        tenDm: 'Dự toán phí nhập xuất',
        tenPl: 'Phụ lục 1',
        status: false,
    },
    {
        id: 'pl02',
        tenDm: 'Phí VTCT',
        tenPl: 'Phụ lục 2',
        status: false,
    },

    {
        id: 'pl03',
        tenDm: 'Dự toán phí bảo quản hàng DTQG',
        tenPl: 'Phụ lục 3',
        status: false,
    },
    {
        id: 'pl04',
        tenDm: 'Dự toán chi ứng dụng CNTT',
        tenPl: 'Phụ lục 4',
        status: false,
    },
    {
        id: 'pl05',
        tenDm: 'Chi sửa chữa kho tàng và các công trình phụ trợ',
        tenPl: 'Phụ lục 5',
        status: false,
    },
    {
        id: 'pl06',
        tenDm: 'Đề xuất nhu cầu trang bị tài sản là máy móc, thiết bị chuyên dùng phục vụ công tác nhập, xuất, bảo quản',
        tenPl: 'Phụ lục 6',
        status: false,
    },
    {
        id: 'pl07',
        tenDm: 'Thuyết minh chi các đề tài, dự án nghiên cứu khoa học',
        tenPl: 'Phụ lục 7',
        status: false,
    },
    {
        id: 'plda',
        tenDm: 'Phương án phân bổ kế hoạch vốn đầu tư công nguồn NSNN',
        tenPl: 'Phụ lục dự án',
        status: false,
    },
    {
        id: 'pl_bh_hang',
        tenDm: 'Danh mục, giá trị hàng DTQG tham gia bảo hiểm',
        tenPl: 'Bảo hiểm hàng',
        status: false,
    },
    {
        id: 'pl_bh_kho',
        tenDm: 'Danh mục, giá trị kho DTQG tham gia bảo hiểm',
        tenPl: 'Bảo hiểm hàng',
        status: false,
    },
    {
        id: 'pl_bh_duoi',
        tenDm: 'Danh mục, giá trị hàng, kho (dưới 5000 M3) DTQG tham gia bảo hiểm',
        tenPl: 'Bảo hiểm',
        status: false,
    },
    {
        id: 'pl_bh_tren',
        tenDm: 'Danh mục, giá trị hàng, kho (trên 5000 M3) DTQG tham gia bảo hiểm',
        tenPl: 'Bảo hiểm',
        status: false,
    },
    {
        id: 'pl_bh',
        tenDm: 'Danh mục, giá trị hàng, kho DTQG tham gia bảo hiểm',
        tenPl: 'Bảo hiểm',
        status: false,
    },
    {
        id: 'TT342_13.1',
        tenDm: 'Cơ sở tính chi sự nghiệp giáo dục - đào tạo và dạy nghề',
        tenPl: 'Biểu mẫu 13.1',
        status: false,
    },
    {
        id: 'TT342_13.3',
        tenDm: 'Cơ sở tính chi sự nghiệp khoa học và công nghệ',
        tenPl: 'Biểu mẫu 13.3',
        status: false,
    },

    {
        id: 'TT342_13.8',
        tenDm: 'Cơ sở tính chi các hoạt động kinh tế',
        tenPl: 'Biểu mẫu 13.8',
        status: false,
    },
    {
        id: 'TT342_13.10',
        tenDm: 'Cơ sở tính chi thực hiện chính sách đối với các đối tượng thuộc lĩnh vực bảo đảm xã hội',
        tenPl: 'Biểu mẫu 13.10',
        status: false,
    },
    {
        id: 'TT342_14',
        tenDm: 'Cơ sở tính chi hoạt động của các cơ quan quản lý nhà nước, đảng, đoàn thể',
        tenPl: 'Biểu mẫu 14',
        status: false,
    },
    {
        id: 'TT342_15.1',
        tenDm: 'Báo cáo biên chế - tiền lương của các cơ quan quản lý nhà nước, đảng, đoàn thể',
        tenPl: 'Biểu mẫu 15.1',
        status: false,
    },
    {
        id: 'TT342_15.2',
        tenDm: 'Báo cáo lao động - tiền lương - nguồn kinh phí đảm bảo của các đơn vị sự nghiệp',
        tenPl: 'Biểu mẫu 15.2',
        status: false,
    },
    {
        id: 'TT69_13',
        tenDm: 'Tổng hợp nhu cầu chi ngân sách nhà nước giai đoạn 03 năm',
        tenPl: 'Biểu mẫu 13',
        status: false,
    },
    {
        id: 'TT69_14',
        tenDm: 'Tông hợp nhu cầu chi đầu tư phát triển giai đoạn 03 năm',
        tenPl: 'Biểu mẫu 14',
        status: false,
    },

    {
        id: 'TT69_16',
        tenDm: 'Tổng hợp nhu cầu chi thường xuyên giai đoạn 03 năm',
        tenPl: 'Biểu mẫu 16',
        status: false,
    },
    {
        id: 'TT69_17',
        tenDm: 'Chi tiết nhu cầu chi thường xuyên giai đoạn 03 năm',
        tenPl: 'Biểu mẫu 17',
        status: false,
    },
    {
        id: 'TT69_18',
        tenDm: 'Tổng hợp mục tiêu, nhiệm vụ chủ yếu và nhu cầu chi mới giai đoạn 03 năm',
        tenPl: 'Biểu mẫu 18',
        status: false,
    },
];