import { FileDinhKem } from "./FileDinhKem";

export class BienBanLayMau {
    id: number;
    canCu: string;
    ccuQdinhGiaoNvuNhap: string;
    ctieuKtra: string;
    cvuDdienCcap: string;
    cvuDdienNhan: string;
    ddiemKtra: string;
    ddiemLayMau: string;
    ddienBenNhan: string;
    ddienCucDtruBenGiao: string;
    ddienCucDtruNnuoc: string;
    ddienDviTchucBenNhan: string;
    kquaNiemPhongMau: string;
    maDonVi: string;
    maDviCcap: string;
    maDviNhan: string;
    maHhoa: string;
    maKho: string;
    maLo: string;
    maNgan: string;
    maQHNS: string;
    ngayBgiaoMau: string;
    ngayLapBban: string;
    ngayLayMau: string;
    pphapLayMau: number;
    sluongLMau: string;
    soBban: string;
    soHd: string;
    soTrang: string;
    tenDdienCcap: string;
    tenDdienNhan: string;
    tinhTrang: string;
    tphongKthuatBquan: string;
    trangThai: string;
    tenDonVi: string;
    ngayHd: string;
    tenDonViCCHang: string;
    tenTrangThai: string;
    trangThaiDuyet: string;
    soQd: string;
    chiTieuChatLuongCanKiemTra: string;
}