export const MESSAGE = {
  TITLE_CONFIRM_LOGOUT: 'Bạn có chắc chắn muốn đăng xuất',
  SYSTEM_ERROR: 'Lỗi hệ thống',
  FORM_REQUIRED_ERROR: "Vui lòng điền đủ thông tin",
  ERROR: 'Lỗi!!!',
  WARNING: 'Chú ý!!',
  NOTIFICATION: 'Thông báo',
  SUCCESS: 'Thành công',
  ADD_SUCCESS: 'Thêm mới thành công',
  UPDATE_SUCCESS: 'Cập nhật thành công',
  DELETE_SUCCESS: 'Xóa thành công',
  DELETE_CONFIRM: 'Bạn có chắc chắn muốn xóa',
  PROCESS_SUCCESS: 'Chuyển xử lý thành công',
  SEND_NUMBER_SUCCESS: 'Chuyển cấp số thành công',
  REVERT_SUCCESS: 'Thu hồi thành công',
  RETURN_SUCCESS: 'Trả lại thành công',
  RETURN_RECEIVE_SUCCESS: 'Trả lời người gửi thành công',
  HAVE_COMMENT: 'Xin ý kiến thành công',
  COPY_SUCCESS: 'Sao chép thành công',
  IMPORT_NUMBER_SUCCESS: 'Cấp số thành công',
  IMPORT_NUMBER_SUCCESS_2: 'Lưu dữ liệu thành công',
  SEND_SUCCESS: 'Trình văn bản thành công',
  RELEASE_SUCCESS: 'Phát hành thành công',
  APPROVE_SUCCESS: 'Duyệt thành công',
  KY_THAY: 'Chuyển ký thay thành công',
  KY_THUALENH: 'Chuyển ký thừa lệnh thành công',
  KY_UYQUYEN: 'Chuyển ký ủy quyền thành công',
  MAXIMUM_FILE_UPLOAD: 'File đính kèm không vượt quá 20MB',
  TRINH_DUYET_SUCCESS: 'Trình duyệt thành công',
  QD_TCDT: 'QD-TCDT',
  ERROR_NOT_EMPTY: 'Dữ liệu không được để trống.',
  TU_CHOI_SUCCESS: 'Từ chối thành công.',
  DATA_EMPTY: 'Data rỗng. Vui lòng thêm data để export.',
  DON_VI_TINH_LUONG_THUC: 'Tấn',
  GUI_DUYET_SUCCESS: 'Gửi duyệt thành công',
  PHE_DUYET_SUCCESS: 'Phê duyệt thành công',
  BAN_HANH_SUCCESS: 'Ban hành thành công'
};
