export const MESSAGE = {
  ACCESS_DENIED: "Bạn không có quyền truy cập chức năng này",
  TITLE_CONFIRM_LOGOUT: 'Bạn có chắc chắn muốn đăng xuất',
  SYSTEM_ERROR: 'Lỗi hệ thống',
  FORM_REQUIRED_ERROR: "Vui lòng điền đủ thông tin",
  TEMPLATE_NULL: "Không tìm thấy file mẫu báo cáo",
  ERROR: 'Lỗi!!!',
  WARNING: 'Chú ý!!',
  NOTIFICATION: 'Thông báo',
  SUCCESS: 'Thành công',
  ADD_SUCCESS: 'Bạn đã lưu thành công!',
  UPDATE_SUCCESS: 'Cập nhật thành công',
  DELETE_SUCCESS: 'Xóa thành công',
  DELETE_CONFIRM: 'Bạn có chắc chắn muốn xóa',
  PROCESS_SUCCESS: 'Chuyển xử lý thành công',
  SEND_NUMBER_SUCCESS: 'Chuyển cấp số thành công',
  REVERT_SUCCESS: 'Thu hồi thành công',
  RETURN_SUCCESS: 'Trả lại thành công',
  RETURN_RECEIVE_SUCCESS: 'Trả lời người gửi thành công',
  HAVE_COMMENT: 'Xin ý kiến thành công',
  COPY_SUCCESS: 'Sao chép thành công',
  IMPORT_NUMBER_SUCCESS: 'Cấp số thành công',
  IMPORT_NUMBER_SUCCESS_2: 'Lưu dữ liệu thành công',
  SEND_SUCCESS: 'Trình văn bản thành công',
  RELEASE_SUCCESS: 'Phát hành thành công',
  SUBMIT_SUCCESS: 'Trình duyệt thành công',
  APPROVE_SUCCESS: 'Duyệt thành công',
  SIGNE_APPROVE_SUCCESS: 'Ký số và ban hành thành công',
  KY_THAY: 'Chuyển ký thay thành công',
  KY_THUALENH: 'Chuyển ký thừa lệnh thành công',
  KY_UYQUYEN: 'Chuyển ký ủy quyền thành công',
  MAXIMUM_FILE_UPLOAD: 'File đính kèm không vượt quá 20MB',
  TRINH_DUYET_SUCCESS: 'Trình duyệt thành công',
  THAO_TAC_SUCCESS: 'Thao tác thành công',
  LUU_VA_GUI_DUYET_SUCCESS: 'Bạn đã lưu và gửi duyệt thành công!',
  DUYET_SUCCESS: 'Bạn duyệt thành công!',
  QD_TCDT: 'QD-TCDT',
  QD_BTC: 'QD-BTC',
  ERROR_NOT_EMPTY: 'Dữ liệu không được để trống.',
  TU_CHOI_SUCCESS: 'Từ chối thành công.',
  DATA_EMPTY: 'Data rỗng. Vui lòng thêm data để export.',
  DON_VI_TINH_LUONG_THUC: 'Tấn',
  ERROR_CALL_SERVICE: 'Có lỗi trong quá trình vấn tin',
  SEARCH_VALIDATE: 'Bạn chưa chọn loại báo cáo',
  ERROR_ADD_VTU: 'Không được chọn trùng loại mặt hàng',
  ERROR_ADD_UNIT: 'Không được chọn trùng Cục DTNN KV',
  NULL_ERROR: 'Không được để trống',
  GIAO_SO_TRAN_CHI_SUCCESS: 'Giao số trần chi thành công!',
  GIAO_SO_TRAN_CHI_TOAN_BO: 'Giao toàn bộ thành công!',
  MESSAGE_DELETE_WARNING: 'Cần lưu trước khi thực hiện thao tác',
  ERROR_ADD_MAT_HANG: 'Không được chọn trùng mặt hàng ',
  COPY_SUCCESS_HDV: 'Sao chép thành công dữ liệu sang mã báo cáo ',
  ALERT: 'Thông báo',
  REJECT_SUCCESS: 'Từ chối thành công',
  NO_REPORT: '',
  RATE_FORM: 'Vui lòng đánh giá biểu mẫu trước khi thực hiện thao tác!',
  FINISH_FORM: 'Vui lòng hoàn tất nhập liệu các biểu mẫu trước khi thực hiện thao tác!',
  TRANG_THAI_TIEP_NHAN: 'Bản ghi đã được tiếp nhận',
  CHUA_CO_BAO_CAO: 'Chưa có bản ghi nào trong năm đã nhập',
  GUI_DUYET_CONFIRM: 'Bạn có muốn gửi duyệt bản ghi ?',
  GUI_DUYET_SUCCESS: 'Thao tác thành công',
  PHE_DUYET_CONFIRM: 'Bạn có muốn phê duyệt bản ghi ?',
  PHE_DUYET_SUCCESS: 'Phê duyệt thành công',
  BAN_HANH_CONFIRM: 'Bạn có muốn ban hành bản ghi ?',
  BAN_HANH_SUCCESS: 'Ban hành thành công',
  TONG_HOP_SUCCESS: 'Tổng hợp thành công',
  TAO_BAO_CAO_SUCCESS: 'Tạo báo cáo thành công',
  UNAUTHORIZED_ERROR: 'Phiên đăng nhập hết hạn hoặc lỗi xác thực.',
  ADD_DIEM_KHO_ERROR: 'Số lượng không được lớn hơn số lượng đề xuất.',
  NOT_FOUND_ERR: 'Không tồn tại bản ghi"',
};
