export const MESSAGE = {
  TITLE_CONFIRM_LOGOUT: 'Bạn có chắc chắn muốn đăng xuất',
  SYSTEM_ERROR: 'Lỗi hệ thống',
  ERROR: 'Lỗi!!!',
  WARNING: 'Chú ý!!',
  SUCCESS: 'Thành công',
  ADD_SUCCESS: 'Thêm mới thành công',
  UPDATE_SUCCESS: 'Cập nhật thành công',
  DELETE_SUCCESS: 'Xóa thành công',
  DELETE_CONFIRM: 'Bạn có chắc chắn muốn xóa',
  PROCESS_SUCCESS: 'Chuyển xử lý thành công',
  SEND_NUMBER_SUCCESS: 'Chuyển cấp số thành công',
  REVERT_SUCCESS: 'Thu hồi thành công',
  RETURN_SUCCESS: 'Trả lại thành công',
  RETURN_RECEIVE_SUCCESS: 'Trả lời người gửi thành công',
  HAVE_COMMENT: 'Xin ý kiến thành công',
  COPY_SUCCESS: 'Sao chép thành công',
  IMPORT_NUMBER_SUCCESS: 'Cấp số thành công',
  IMPORT_NUMBER_SUCCESS_2: 'Lưu dữ liệu thành công',
  SEND_SUCCESS: 'Trình văn bản thành công',
  RELEASE_SUCCESS: 'Phát hành thành công',
  APPROVE_SUCCESS: 'Duyệt thành công',
  KY_THAY: 'Chuyển ký thay thành công',
  KY_THUALENH: 'Chuyển ký thừa lệnh thành công',
  KY_UYQUYEN: 'Chuyển ký ủy quyền thành công',
  MAXIMUM_FILE_UPLOAD: 'File đính kèm không vượt quá 20MB',
  TRINH_DUYET_SUCCESS: 'Trình duyệt thành công',
  QD_TCDT: '/QD-TCDT',
  ERROR_NOT_EMPTY: 'Dữ liệu không được để trống.',
  ERROR_CALL_SERVICE: 'Có lỗi trong quá trình vấn tin',
  ERROR_ADD_VTU: 'Không được chọn trùng loại vật tư',
  ERROR_ADD_UNIT: 'Không được chọn trùng Cục DTNN KV',
};
