import { DauThau } from './dau-thau.type';

export const MUOI_LIST: DauThau[] = [
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'QĐ PHÊ DUYỆT KH LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'QĐ điều chỉnh phê duyệt KH LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Thông tin đấu thầu',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'QĐ phê duyệt kết quả LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Hợp đồng mua',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Biên bản giao nhận',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Hồ sơ kỹ thuật',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Lệnh nhập',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Biên bản chuẩn bị kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    isDisabled: true,
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Biên bản nghiệm thu kê lót BQ ban đầu nhập lương thực',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Phiếu kiểm tra chất lượng hàng DTQG nhập kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Phiếu nhập điều chỉnh',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
  },
];

export const LUONG_THUC_LIST: DauThau[] = [
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'ĐỀ XUẤT KẾ HOẠCH LỰA CHỌN NHÀ THẦU',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'danh-sach-dau-thau',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Tổng hợp KH LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'luong-dau-thau-gao',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'QĐ phê duyệt KH LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quyet-dinh-phe-duyet-ke-hoach-lua-chon-nha-thau',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'QĐ điều chỉnh phê duyệt KH LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Thông tin đấu thầu',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'thong-tin-dau-thau',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Hợp đồng mua',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'hop-dong-mua',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Biên bản giao nhận',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Hồ sơ kỹ thuật',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Lệnh nhập',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    isDisabled: true,
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'QĐ phê duyệt kết quả LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quyet-dinh-phe-duyet-ket-qua-lcnt',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Biên bản chuẩn bị kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Biên bản nghiệm thu kê lót BQ ban đầu nhập lương thực',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quan-ly-bien-ban-nghiem-thu-ke-lot',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Phiếu kiểm tra chất lượng hàng DTQG nhập kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quan-ly-phieu-kiem-tra-chat-luong-hang',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Phiếu nhập điều chỉnh',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Phương án trình tổng cục',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'phuong-an-trinh-tong-cuc',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quyết định giao nhiệm vụ nhập hàng',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quyet-dinh-giao-nhiem-vu-nhap-hang',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quản lý phiếu nhập kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quan-ly-phieu-nhap-kho',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quản lý bảng kê cân hàng',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quan-ly-bang-ke-can-hang',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quản lý biên bản lấy mẫu',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quan-ly-bien-ban-lay-mau',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quản lý phiếu kiểm nghiệm chất lượng',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quan-ly-phieu-kiem-nghiem-chat-luong',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quản lý phiếu nhập đầy kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quan-ly-phieu-nhap-day-kho',
  },
];

export const VAT_TU_LIST: DauThau[] = [
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Đề xuất KH LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'vat-tu/ke-hoach-lua-chon-nha-thau-vat-tu',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'QĐ PHÊ DUYỆT KH LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'vat-tu/quyet-dinh-phe-duyet-ke-hoach-lcnt',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'QĐ điều chỉnh phê duyệt KH LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Thông tin đấu thầu',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'vat-tu/thong-tin-lcnt',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'QĐ phê duyệt kết quả LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'vat-tu/quyet-dinh-phe-duyet-ket-qua-lcnt',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Hợp đồng mua',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'vat-tu/hop-dong-mua',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Biên bản giao nhận',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Hồ sơ kỹ thuật',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'vat-tu/ho-so-ky-thuat',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Lệnh nhập',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Biên bản chuẩn bị kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    isDisabled: true,
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Biên bản nghiệm thu kê lót BQ ban đầu nhập lương thực',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Phiếu kiểm tra chất lượng hàng DTQG nhập kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Phiếu nhập điều chỉnh',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Phiếu nhập kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'vat-tu/phieu-nhap-kho',
  },
];
