export const DAU_THAU_LIST = [
  {
    icon: 'htvbdh_office',
    title: 'QĐ PHÊ DUYỆT KH LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    isActive: false,
    url: '',
  },
  {
    icon: 'htvbdh_office',
    title: 'QĐ điều chỉnh phê duyệt KH LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    isActive: false,
    url: '',
  },
  {
    icon: 'htvbdh_office',
    title: 'Thông tin đấu thầu',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    isActive: false,
    url: '',
  },
  {
    icon: 'htvbdh_office',
    title: 'QĐ phê duyệt kết quả LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    isActive: false,
    url: '',
  },
  {
    icon: 'htvbdh_office',
    title: 'Hợp đồng mua',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    isActive: false,
    url: '',
  },
  {
    icon: 'htvbdh_office',
    title: 'Biên bản giao nhận',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    isActive: false,
    url: '',
  },
  {
    icon: 'htvbdh_office',
    title: 'Hồ sơ kỹ thuật',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    isActive: false,
    url: '',
  },
  {
    icon: 'htvbdh_office',
    title: 'Lệnh nhập',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    isActive: false,
    url: '',
  },
  {
    icon: 'htvbdh_office',
    title: 'Biên bản chuẩn bị kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    isActive: false,
    url: '',
  },
  {
    icon: 'htvbdh_office',
    title: 'Biên bản nghiệm thu kê lót BQ ban đầu nhập lương thực',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    isActive: false,
    url: '',
  },
  {
    icon: 'htvbdh_office',
    title: 'Phiếu kiểm tra chất lượng hàng DTQG nhập kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    isActive: false,
    url: '',
  },
  {
    icon: 'htvbdh_office',
    title: 'Phiếu nhập điều chỉnh',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    isActive: false,
    url: '',
  },
];
