export const LINH_VUC = [
    {
        id: 1000,
        tenDm: "Quốc phòng",
        idCha: 0,
        level: 0,
    },
    {
        id: 1100,
        tenDm: "Chi thường xuyên cơ sở",
        idCha: 1000,
        level: 1,
    },
    {
        id: 1110,
        tenDm: "Dự toán/dự kiến bố trí",
        idCha: 1100,
        level: 2,
    },
    {
        id: 1120,
        tenDm: "Các điều chỉnh chi tiêu cơ sở",
        idCha: 1100,
        level: 2,
    },
    {
        id: 1121,
        tenDm: "Thay đổi kỹ thuật (chi tiết theo từng đề xuất cụ thể)",
        idCha: 1120,
        level: 3,
    },
    {
        id: 1122,
        tenDm: "Thực hiện cắt giảm dự toán để đảm bảo mục tiêu cân đối NSNN theo quyết định của cơ quan có thẩm quyền",
        idCha: 1120,
        level: 3,
    },
    {
        id: 1200,
        tenDm: "Chi thường xuyên mới",
        idCha: 1000,
        level: 1,
    },
    {
        id: 1210,
        tenDm: "Kinh phí để thực hiện các nhiệm vụ, hoạt động, chế độ, chính sách đã ban hành trước đây nhưng đến giai đoạn kế hoạch này mới bố trí được nguồn để triển khai",
        idCha: 1200,
        level: 2,
    },
    {
        id: 1220,
        tenDm: "Kinh phí duy trì thực hiện các nhiệm vụ, hoạt động mới được bổ sung ở năm hiện hành, tiếp tục thực hiện năm dự toán và các năm tiếp theo.",
        idCha: 1200,
        level: 2,
    },
    {
        id: 1230,
        tenDm: "Kinh phí tăng thêm khi tăng quy mô biên chế của cơ quan, đơn vị theo quyết định của cơ quan nhà nước có thẩm quyền",
        idCha: 1200,
        level: 2,
    },
    {
        id: 1240,
        tenDm: "Kinh phí duy tu bảo dưỡng máy móc, trang thiết bị để vận hành các dự án đầu tư mới hoàn thành, đưa vào sử dụng trong năm dự toán;",
        idCha: 1200,
        level: 2,
    },
    {
        id: 1250,
        tenDm: "Kinh phí cho các nhiệm vụ, hoạt động, chế độ, chính sách bắt đầu thực hiện trong năm dự toán, bao gồm cả kinh phí sự nghiệp đối ứng cho các dự án mới sử dụng vốn ngoài nước",
        idCha: 1200,
        level: 2,
    },
    {
        id: 1260,
        tenDm: "Kinh phí thực hiện cải cách mức tiền lương cơ sở theo quyết định của cấp có thẩm quyền.",
        idCha: 1200,
        level: 2,
    },
    {
        id: 2000,
        tenDm: "An ninh và trật tự, an toàn xã hội",
        idCha: 0,
        level: 0,
    },
    {
        id: 2100,
        tenDm: "Chi thường xuyên cơ sở",
        idCha: 2000,
        level: 1,
    },
    {
        id: 2110,
        tenDm: "Dự toán/dự kiến bố trí",
        idCha: 2100,
        level: 2,
    },
    {
        id: 2120,
        tenDm: "Các điều chỉnh chi tiêu cơ sở",
        idCha: 2100,
        level: 2,
    },
    {
        id: 2121,
        tenDm: "Thay đổi kỹ thuật (chi tiết theo từng đề xuất cụ thể)",
        idCha: 2120,
        level: 3,
    },
    {
        id: 2122,
        tenDm: "Thực hiện cắt giảm dự toán để đảm bảo mục tiêu cân đối NSNN theo quyết định của cơ quan có thẩm quyền",
        idCha: 2120,
        level: 3,
    },
    {
        id: 2200,
        tenDm: "Chi thường xuyên mới",
        idCha: 2000,
        level: 2,
    },
    {
        id: 2210,
        tenDm: "Kinh phí để thực hiện các nhiệm vụ, hoạt động, chế độ, chính sách đã ban hành trước đây nhưng đến giai đoạn kế hoạch này mới bố trí được nguồn để triển khai",
        idCha: 2200,
        level: 2,
    },
    {
        id: 2220,
        tenDm: "Kinh phí duy trì thực hiện các nhiệm vụ, hoạt động mới được bổ sung ở năm hiện hành, tiếp tục thực hiện năm dự toán và các năm tiếp theo.",
        idCha: 2200,
        level: 2,
    },
    {
        id: 2230,
        tenDm: "Kinh phí tăng thêm khi tăng quy mô biên chế của cơ quan, đơn vị theo quyết định của cơ quan nhà nước có thẩm quyền",
        idCha: 2200,
        level: 2,
    },
    {
        id: 2240,
        tenDm: "Kinh phí duy tu bảo dưỡng máy móc, trang thiết bị để vận hành các dự án đầu tư mới hoàn thành, đưa vào sử dụng trong năm dự toán;",
        idCha: 2200,
        level: 2,
    },
    {
        id: 2250,
        tenDm: "Kinh phí cho các nhiệm vụ, hoạt động, chế độ, chính sách bắt đầu thực hiện trong năm dự toán, bao gồm cả kinh phí sự nghiệp đối ứng cho các dự án mới sử dụng vốn ngoài nước",
        idCha: 2200,
        level: 2,
    },
    {
        id: 2260,
        tenDm: "Kinh phí thực hiện cải cách mức tiền lương cơ sở theo quyết định của cấp có thẩm quyền.",
        idCha: 2200,
        level: 2,
    },
    {
        id: 3000,
        tenDm: "Sự nghiệp giáo dục - đào tạo và dạy nghề",
        idCha: 0,
        level: 0,
    },
    {
        id: 3100,
        tenDm: "Chi thường xuyên cơ sở",
        idCha: 3000,
        level: 1,
    },
    {
        id: 3110,
        tenDm: "Dự toán/dự kiến bố trí",
        idCha: 3100,
        level: 2,
    },
    {
        id: 3120,
        tenDm: "Các điều chỉnh chi tiêu cơ sở",
        idCha: 3100,
        level: 2,
    },
    {
        id: 3121,
        tenDm: "Thay đổi kỹ thuật (chi tiết theo từng đề xuất cụ thể)",
        idCha: 3120,
        level: 3,
    },
    {
        id: 3122,
        tenDm: "Thực hiện cắt giảm dự toán để đảm bảo mục tiêu cân đối NSNN theo quyết định của cơ quan có thẩm quyền",
        idCha: 3120,
        level: 3,
    },
    {
        id: 3200,
        tenDm: "Chi thường xuyên mới",
        idCha: 3000,
        level: 2,
    },
    {
        id: 3210,
        tenDm: "Kinh phí để thực hiện các nhiệm vụ, hoạt động, chế độ, chính sách đã ban hành trước đây nhưng đến giai đoạn kế hoạch này mới bố trí được nguồn để triển khai",
        idCha: 3200,
        level: 2,
    },
    {
        id: 3220,
        tenDm: "Kinh phí duy trì thực hiện các nhiệm vụ, hoạt động mới được bổ sung ở năm hiện hành, tiếp tục thực hiện năm dự toán và các năm tiếp theo.",
        idCha: 3200,
        level: 2,
    },
    {
        id: 3230,
        tenDm: "Kinh phí tăng thêm khi tăng quy mô biên chế của cơ quan, đơn vị theo quyết định của cơ quan nhà nước có thẩm quyền",
        idCha: 3200,
        level: 2,
    },
    {
        id: 3240,
        tenDm: "Kinh phí duy tu bảo dưỡng máy móc, trang thiết bị để vận hành các dự án đầu tư mới hoàn thành, đưa vào sử dụng trong năm dự toán;",
        idCha: 3200,
        level: 2,
    },
    {
        id: 3250,
        tenDm: "Kinh phí cho các nhiệm vụ, hoạt động, chế độ, chính sách bắt đầu thực hiện trong năm dự toán, bao gồm cả kinh phí sự nghiệp đối ứng cho các dự án mới sử dụng vốn ngoài nước",
        idCha: 3200,
        level: 2,
    },
    {
        id: 3260,
        tenDm: "Kinh phí thực hiện cải cách mức tiền lương cơ sở theo quyết định của cấp có thẩm quyền.",
        idCha: 3200,
        level: 2,
    },
]