export const NOI_DUNG = [
    {
        id: 10,
        tenDm: "Giáo dục - đào tạo dạy nghề",
        level: 0,
        idCha: 0,
        loai: 0,
    },
    {
        id: 11,
        tenDm: "Chi thường xuyên cơ sở",
        level: 1,
        idCha: 10,
        loai: 1,
    },
    {
        id: 12,
        tenDm: "Chi thường xuyên mới",
        level: 1,
        idCha: 10,
        loai: 2,
    },
    {
        id: 20,
        tenDm: "Khoa học và công nghệ",
        level: 0,
        idCha: 0,
        loai: 0,
    },
    {
        id: 21,
        tenDm: "Chi thường xuyên cơ sở",
        level: 1,
        idCha: 20,
        loai: 1,
    },
    {
        id: 22,
        tenDm: "Chi thường xuyên mới",
        level: 1,
        idCha: 20,
        loai: 2,
    },
    {
        id: 30,
        tenDm: "Các hoạt động kinh tế",
        level: 0,
        idCha: 0,
        loai: 0,
    },
    {
        id: 31,
        tenDm: "Chi thường xuyên cơ sở",
        level: 1,
        idCha: 30,
        loai: 1,
    },
    {
        id: 32,
        tenDm: "Chi thường xuyên mới",
        level: 1,
        idCha: 30,
        loai: 2,
    },
    {
        id: 40,
        tenDm: "Hoạt động của các cơ quan nhà nước, đảng đoàn thể",
        level: 0,
        idCha: 0,
        loai: 0,
    },
    {
        id: 41,
        tenDm: "Chi thường xuyên cơ sở",
        level: 1,
        idCha: 40,
        loai: 1,
    },
    {
        id: 42,
        tenDm: "Chi thường xuyên mới",
        level: 1,
        idCha: 40,
        loai: 2,
    },
    {
        id: 50,
        tenDm: "Quốc phòng",
        level: 0,
        idCha: 0,
        loai: 0,
    },
    {
        id: 51,
        tenDm: "Chi thường xuyên cơ sở",
        level: 1,
        idCha: 50,
        loai: 1,
    },
    {
        id: 52,
        tenDm: "Chi thường xuyên mới",
        level: 1,
        idCha: 50,
        loai: 2,
    },
    {
        id: 60,
        tenDm: "An ninh trật tự và an toàn xã hội",
        level: 0,
        idCha: 0,
        loai: 0,
    },
    {
        id: 61,
        tenDm: "Chi thường xuyên cơ sở",
        level: 1,
        idCha: 60,
        loai: 1,
    },
    {
        id: 62,
        tenDm: "Chi thường xuyên mới",
        level: 1,
        idCha: 60,
        loai: 2,
    },
]
