export const NOI_DUNG = [
    {
        id: 100,
        tenDm: "TRẦN CHI NGÂN SÁCH ĐƯỢC THÔNG BÁO",
        level: 0,
        idCha: 0,
    },
    {
        id: 200,
        tenDm: "NHU CẦU CHI CỦA CƠ QUAN, ĐƠN VỊ",
        level: 0,
        idCha: 0,
    },
    {
        id: 210,
        tenDm: "Chi đầu tư phát triển cơ sở",
        level: 1,
        idCha: 200,
    },
    {
        id: 211,
        tenDm: "Vốn thanh toán nợ đọng XDCB theo quy định nhưng đến hết kế hoạch năm trước chưa bố trí được nguồn để thanh toán",
        level: 2,
        idCha: 210,
    },
    {
        id: 212,
        tenDm: "Vốn thu hồi các khoản ứng trước dự toán để đẩy nhanh tiến độ các dự án đang thực hiện theo quy định tại Điều 37 Nghị định số 163/2016/NĐ-CP của Chính phủ",
        level: 2,
        idCha: 210,
    },
    {
        id: 213,
        tenDm: "Vốn đầu tư cho các dự án chuyển tiếp, các dự án khởi công mới trong năm hiện hành; tiếp tục thực hiện trong năm tiếp theo",
        level: 2,
        idCha: 210,
    },
    {
        id: 214,
        tenDm: "Vốn thực hiện các khoản chi đầu tư phát triển khác theo quy định của pháp luật",
        level: 2,
        idCha: 210,
    },
    {
        id: 220,
        tenDm: "Chi đầu tư phát triển mới",
        level: 1,
        idCha: 200,
    },
    {
        id: 221,
        tenDm: "Vốn đầu tư của dự án được bố trí vốn bắt đầu thực hiện (khởi công mới) năm hiện hành nhưng không triển khai được và không được chuyển nguồn sang năm sau theo quy định",
        level: 2,
        idCha: 220,
    },
    {
        id: 222,
        tenDm: "Vốn thu hồi các khoản ứng trước dự toán để khởi công mới các dự án theo quy định tại Điều 37 Nghị định số 163/2016/NĐ-CP của Chính phủ",
        level: 2,
        idCha: 220,
    },
    {
        id: 223,
        tenDm: "Vốn đầu tư cho các dự án bắt đầu thực hiện trong năm dự toán",
        level: 2,
        idCha: 220,
    },
    {
        id: 224,
        tenDm: "Dự án được cấp có thẩm quyền xem xét, phê duyệt trong thời gian xen giữa 02 kế hoạch đầu tư công trung hạn và chắc chắn được bố trí vốn trong kế hoạch đầu tư công trung hạn giai đoạn sau, có nhu cầu triển khai thực hiện ngay từ năm đầu tiên của kế hoạch trung hạn giai đoạn sau",
        level: 2,
        idCha: 220,
    },
    {
        id: 225,
        tenDm: "Nghiên cứu khả thi cho các dự án được triển khai trong kế hoạch trung hạn sau",
        level: 2,
        idCha: 220,
    },
    {
        id: 300,
        tenDm: "CHÊNH LỆCH TRẦN CHI-NHU CẦU",
        level: 0,
        idCha: 0,
    },
]