export const MUOI_LIST = [
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'QĐ PHÊ DUYỆT KH LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'QĐ điều chỉnh phê duyệt KH LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Thông tin đấu thầu',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'QĐ phê duyệt kết quả LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Hợp đồng mua',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Biên bản giao nhận',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Hồ sơ kỹ thuật',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Lệnh nhập',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Biên bản chuẩn bị kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    isDisabled: true,
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Biên bản nghiệm thu kê lót BQ ban đầu nhập lương thực',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Phiếu kiểm tra chất lượng hàng DTQG nhập kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Phiếu nhập điều chỉnh',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
];

export const THOC_LIST = [
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'ĐỀ XUẤT KẾ HOẠCH LỰA CHỌN NHÀ THẦU',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'danh-sach-dau-thau',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Tổng hợp KH LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'luong-dau-thau-gao',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'QĐ phê duyệt KH LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quyet-dinh-phe-duyet-ke-hoach-lua-chon-nha-thau',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'QĐ điều chỉnh phê duyệt KH LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Thông tin đấu thầu',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'thong-tin-dau-thau',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Hợp đồng mua',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'hop-dong-mua',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Biên bản giao nhận',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Hồ sơ kỹ thuật',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Lệnh nhập',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    isDisabled: true,
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'QĐ phê duyệt kết quả LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quyet-dinh-phe-duyet-ket-qua-lcnt',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Biên bản chuẩn bị kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Biên bản nghiệm thu kê lót BQ ban đầu nhập lương thực',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quan-ly-bien-ban-nghiem-thu-ke-lot',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Phiếu kiểm tra chất lượng hàng DTQG nhập kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quan-ly-phieu-kiem-tra-chat-luong-hang',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Phiếu nhập điều chỉnh',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Phương án trình tổng cục',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'phuong-an-trinh-tong-cuc',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quyết định giao nhiệm vụ nhập hàng',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quyet-dinh-giao-nhiem-vu-nhap-hang',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quản lý phiếu nhập kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quan-ly-phieu-nhap-kho',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quản lý bảng kê cân hàng',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quan-ly-bang-ke-can-hang',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quản lý biên bản lấy mẫu',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quan-ly-bien-ban-lay-mau',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quản lý phiếu kiểm nghiệm chất lượng',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quan-ly-phieu-kiem-nghiem-chat-luong',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quản lý phiếu nhập đầy kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quan-ly-phieu-nhap-day-kho',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
];

export const GAO_LIST = [
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'ĐỀ XUẤT KẾ HOẠCH LỰA CHỌN NHÀ THẦU',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'danh-sach-dau-thau',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Tổng hợp KH LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'luong-dau-thau-gao',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'QĐ phê duyệt KH LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quyet-dinh-phe-duyet-ke-hoach-lua-chon-nha-thau',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'QĐ điều chỉnh phê duyệt KH LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Thông tin đấu thầu',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'thong-tin-dau-thau',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Hợp đồng mua',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'hop-dong-mua',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Biên bản giao nhận',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Hồ sơ kỹ thuật',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Lệnh nhập',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    isDisabled: true,
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'QĐ phê duyệt kết quả LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quyet-dinh-phe-duyet-ket-qua-lcnt',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Biên bản chuẩn bị kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Biên bản nghiệm thu kê lót BQ ban đầu nhập lương thực',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quan-ly-bien-ban-nghiem-thu-ke-lot',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Phiếu kiểm tra chất lượng hàng DTQG nhập kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quan-ly-phieu-kiem-tra-chat-luong-hang',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Phiếu nhập điều chỉnh',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Phương án trình tổng cục',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'phuong-an-trinh-tong-cuc',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quyết định giao nhiệm vụ nhập hàng',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quyet-dinh-giao-nhiem-vu-nhap-hang',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quản lý phiếu nhập kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quan-ly-phieu-nhap-kho',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quản lý bảng kê cân hàng',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quan-ly-bang-ke-can-hang',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quản lý biên bản lấy mẫu',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quan-ly-bien-ban-lay-mau',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quản lý phiếu kiểm nghiệm chất lượng',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quan-ly-phieu-kiem-nghiem-chat-luong',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quản lý phiếu nhập đầy kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'quan-ly-phieu-nhap-day-kho',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
];

export const VAT_TU_LIST = [
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Đề xuất KH LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'vat-tu/ke-hoach-lua-chon-nha-thau-vat-tu',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'QĐ PHÊ DUYỆT KH LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'vat-tu/quyet-dinh-phe-duyet-ke-hoach-lcnt',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'QĐ điều chỉnh phê duyệt KH LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Thông tin đấu thầu',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'vat-tu/thong-tin-lcnt',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'QĐ phê duyệt kết quả LCNT',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'vat-tu/quyet-dinh-phe-duyet-ket-qua-lcnt',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Hợp đồng mua',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'vat-tu/hop-dong-mua',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Biên bản giao nhận',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Hồ sơ kỹ thuật',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'vat-tu/ho-so-ky-thuat',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Lệnh nhập',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Biên bản chuẩn bị kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    isDisabled: true,
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Biên bản nghiệm thu kê lót BQ ban đầu nhập lương thực',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Phiếu kiểm tra chất lượng hàng DTQG nhập kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Phiếu nhập điều chỉnh',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Phiếu nhập kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'vat-tu/phieu-nhap-kho',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quản lý bảng kê cân hàng',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'vat-tu/quan-ly-bang-can-ke-hang',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quản lý biên bản kết thúc nhập kho',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'vat-tu/bien-ban-ket-thuc-nhap-kho',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quản lý biên bản giao nhận',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'vat-tu/bien-ban-giao-nhan',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quyết định giao nhiệm vụ nhập hàng',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'vat-tu/quyet-dinh-giao-nhiem-vu-nhap-hang',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Biên bản chuẩn bị kho trước khi nhập hàng',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'vat-tu/bien-ban-chuan-bi-kho-truoc-khi-nhap-hang',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quản lý phiếu nhập kho tạm gửi',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'vat-tu/phieu-nhap-kho-tam-gui',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quản lý biên bản gửi hàng',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'vat-tu/bien-ban-gui-hang',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Quản lý biên bản bàn giao mẫu',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: 'vat-tu/bien-ban-ban-giao-mau',
  },
];

export const DAU_THAU_LIST = [
  {
    icon: 'htvbdh_tcdt_baothoc',
    title: 'Thóc',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_baogao',
    title: 'Gạo',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_muoi',
    title: 'Muối',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
  {
    icon: 'htvbdh_tcdt_ngan-kho',
    title: 'Vật tư',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
]

export const MUA_TRUC_TIEP_LIST = [
  {
    icon: 'htvbdh_tcdt_baothoc',
    title: 'Thóc',
    description: 'Danh sách quyết định phê duyệt kế hoạch lựa chọn nhà thầu',
    url: '',
    urlTongCuc: '',
    urlCuc: '',
    urlChiCuc: '',
  },
]
