export const NOI_DUNG = [
    {
        id: 1000,
        tenDm: "HOẠT ĐỘNG DỰ TRỮ QUỐC GIA (Khoản 331)",
        idCha: 0,
        level: 0,
        ma: '0.1',
    },
    {
        id: 1100,
        tenDm: "Kinh phí thực hiện tự chủ",
        idCha: 1000,
        level: 1,
        ma: '0.1.1',
    },
    {
        id: 1200,
        tenDm: "Kinh phí không thực hiện tự chủ",
        idCha: 1000,
        level: 1,
        ma: '0.1.2',
    },
    // {
    //     id: 12001,
    //     tenDm: "Chi ứng dụng công nghệ thông tin",
    //     idCha: 1200,
    //     level: 2,
    //     ma: '0.1.2.1',
    // },
    {
        id: 12002,
        tenDm: "Chi sửa chữa kho tàng và các công trình phụ trợ",
        idCha: 1200,
        level: 2,
        ma: '0.1.2.1',
    },
    {
        id: 12003,
        tenDm: "Chi bảo quản hàng dự trữ, phí nhập xuất hàng, phí xuất hàng cứu trợ, viện trợ, hỗ trợ chính sách",
        idCha: 1200,
        level: 2,
        ma: '0.1.2.2',
    },
    {
        id: 1200301,
        tenDm: "Phí bảo quản",
        idCha: 12003,
        level: 3,
        ma: '0.1.2.2.1',
    },
    {
        id: 1200302,
        tenDm: "Phí nhập",
        idCha: 12003,
        level: 3,
        ma: '0.1.2.2.2',
    },
    {
        id: 1200303,
        tenDm: "Phí xuất",
        idCha: 12003,
        level: 3,
        ma: '0.1.2.2.3',
    },
    {
        id: 1200304,
        tenDm: "Phí viện trợ, cứu trợ",
        idCha: 12003,
        level: 3,
        ma: '0.1.2.2.4',
    },
    {
        id: 12004,
        tenDm: "Chi CNTT",
        idCha: 1200,
        level: 2,
        ma: '0.1.2.3',
    },
    {
        id: 12005,
        tenDm: "Chi khác",
        idCha: 1200,
        level: 2,
        ma: '0.1.2.4',
    },
    {
        id: 1200501,
        tenDm: "Mua sắm tài sản(theo 149)",
        idCha: 12005,
        level: 3,
        ma: '0.1.2.4.1',
    },
    {
        id: 1200502,
        tenDm: "Mua BHHH (Bảo hiểm hàng hóa)",
        idCha: 12005,
        level: 3,
        ma: '0.1.2.4.2',
    },
    {
        id: 1200503,
        tenDm: "Phòng chống bão lụt",
        idCha: 12005,
        level: 3,
        ma: '0.1.2.4.3',
    },
    {
        id: 1200504,
        tenDm: "Khác",
        idCha: 12005,
        level: 3,
        ma: '0.1.2.4.4',
    },
    //============
    {
        id: 2000,
        tenDm: "QUẢN LÝ HÀNH CHÍNH (Khoản 341)",
        idCha: 0,
        level: 0,
        ma: '0.2',
    },
    {
        id: 2100,
        tenDm: "Kinh phí thực hiện tự chủ",
        idCha: 2000,
        level: 1,
        ma: '0.2.1',
    },
    {
        id: 21001,
        tenDm: "Quỹ lương",
        idCha: 2100,
        level: 2,
        ma: '0.2.1.1',
    },
    {
        id: 21002,
        tenDm: "Chi quản lý hành chính theo định mức",
        idCha: 2100,
        level: 2,
        ma: '0.2.1.2',
    },
    {
        id: 2200,
        tenDm: "Kinh phí không thực hiện tự chủ",
        idCha: 2000,
        level: 1,
        ma: '0.2.2',
    },
    {
        id: 22001,
        tenDm: "Chi hỗ trợ đảm bảo một phần chi thường xuyên của đơn vị sự nghiệp",
        idCha: 2200,
        level: 2,
        ma: '0.2.2.1',
    },
    {
        id: 22002,
        tenDm: "Chi thực hiện chính sách tinh giảm biên chế",
        idCha: 2200,
        level: 2,
        ma: '0.2.2.2',
    },
    //=============
    {
        id: 3000,
        tenDm: "SỰ NGHIỆP KHOA HỌC CÔNG NGHỆ (Khoản 102)",
        idCha: 0,
        level: 0,
        ma: '0.3',
    },
    {
        id: 3100,
        tenDm: "Nhiệm vụ khoa học công nghệ",
        idCha: 3000,
        level: 1,
        ma: '0.3.1',
    },
    {
        id: 31001,
        tenDm: "Chi thực hiện nhiệm vụ khoa học công nghệ cấp cơ sở",
        idCha: 3100,
        level: 2,
        ma: '0.3.1.1',
    },
    //=============
    {
        id: 4000,
        tenDm: "SỰ NGHIỆP GIÁO DỤC ĐÀO TẠO (Khoản 085)",
        idCha: 0,
        level: 0,
        ma: '0.4',
    },
    {
        id: 4100,
        tenDm: "Kinh phí thực hiện tự chủ",
        idCha: 4000,
        level: 1,
        ma: '0.4.1',
    },
    {
        id: 4200,
        tenDm: "Kinh phí không thực hiện tự chủ",
        idCha: 4000,
        level: 1,
        ma: '0.4.2',
    },
    {
        id: 41001,
        tenDm: "Chi đào tạo, bồi dưỡng cán bộ, công chức nhà nước",
        idCha: 4200,
        level: 2,
        ma: '0.4.2.1',
    },
    //=============
    {
        id: 5000,
        tenDm: "HOẠT ĐỘNG ĐẢM BẢO XÃ HỘI (Khoản 398)",
        idCha: 0,
        level: 0,
        ma: '0.5',
    },
    {
        id: 5100,
        tenDm: "Kinh phí thực hiện tự chủ",
        idCha: 5000,
        level: 1,
        ma: '0.5.1',
    },
    {
        id: 5200,
        tenDm: "Kinh phí không thực hiện tự chủ",
        idCha: 5000,
        level: 1,
        ma: '0.5.2',
    },
]
