import { ChiTietMenu } from "src/app/models/ChiTietMenu";

export const MUA_HANG_ROUTE_LIST: Array<ChiTietMenu> = [
    {
        icon: 'htvbdh_tcdt_dauthau',
        title: 'Theo phương thức đấu thầu',
        url: `/dau-thau`,
        dropdown: 'dau-thau',
        idHover: 'dauthau',
        hasTab: true,
        children: [
            {
                title: 'Thóc',
                loaiVthh: 'thoc',
                icon: '',
                hasChild: true,
                url: '',
                urlTongCuc: '',
                urlCuc: '',
                urlChiCuc: '',
                children: [
                    {
                        icon: 'htvbdh_tcdt_nhomquyen',
                        title: 'Kế hoạch lựa chọn nhà thầu',
                        url: '/dau-thau/kehoach-luachon-nhathau/thoc',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_nhomquyen2',
                        title: 'Tổ chức triển khai lựa chọn nhà thầu cục',
                        url: '/dau-thau/trienkhai-luachon-nhathau/thoc',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_nhomquyen2',
                        title: 'Điều chỉnh kế hoạch lựa chọn nhà thầu',
                        url: '/dau-thau/dieuchinh-luachon-nhathau/thoc',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                ]
            },
            {
                title: 'Gạo',
                loaiVthh: 'gao',
                icon: '',
                hasChild: true,
                url: '',
                urlTongCuc: '',
                urlCuc: '',
                urlChiCuc: '',
                children: [
                    {
                        icon: 'htvbdh_tcdt_nhomquyen',
                        title: 'Kế hoạch lựa chọn nhà thầu',
                        url: '/dau-thau/kehoach-luachon-nhathau/gao',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_nhomquyen2',
                        title: 'Tổ chức triển khai lựa chọn nhà thầu',
                        url: '/dau-thau/trienkhai-luachon-nhathau/gao',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_nhomquyen2',
                        title: 'Điều chỉnh kế hoạch lựa chọn nhà thầu',
                        url: '/dau-thau/dieuchinh-luachon-nhathau/gao',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                ]
            },
            {
                title: 'Muối',
                loaiVthh: 'muoi',
                icon: '',
                hasChild: true,
                url: '',
                urlTongCuc: '',
                urlCuc: '',
                urlChiCuc: '',
                children: [
                    {
                        icon: 'htvbdh_tcdt_nhomquyen',
                        title: 'Kế hoạch lựa chọn nhà thầu',
                        url: '/dau-thau/kehoach-luachon-nhathau/muoi',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_nhomquyen2',
                        title: 'Tổ chức triển khai lựa chọn nhà thầu',
                        url: '/dau-thau/trienkhai-luachon-nhathau/muoi',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_nhomquyen2',
                        title: 'Điều chỉnh kế hoạch lựa chọn nhà thầu',
                        url: '/dau-thau/dieuchinh-luachon-nhathau/muoi',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                ]
            },
            {
                title: 'Vật tư',
                loaiVthh: 'vat-tu',
                icon: '',
                hasChild: true,
                url: '',
                urlTongCuc: '',
                urlCuc: '',
                urlChiCuc: '',
                children: [
                    {
                        icon: 'htvbdh_tcdt_nhomquyen',
                        title: 'Kế hoạch lựa chọn nhà thầu',
                        url: '/dau-thau/kehoach-luachon-nhathau/vat-tu',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_nhomquyen2',
                        title: 'Tổ chức triển khai lựa chọn nhà thầu',
                        url: '/dau-thau/trienkhai-luachon-nhathau/vat-tu',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_nhomquyen2',
                        title: 'Điều chỉnh kế hoạch lựa chọn nhà thầu',
                        url: '/dau-thau/dieuchinh-luachon-nhathau/vat-tu',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                ]
            },
        ]
    },
    {
        icon: 'htvbdh_tcdt_muatructiep',
        title: 'Theo phương thức mua trực tiếp',
        url: `/mua-truc-tiep`,
        dropdown: 'mua-truc-tiep',
        idHover: 'muatructiep',
        hasTab: true,
        children: [
            {
                title: 'Thóc',
                icon: '',
                hasChild: true,
                url: '',
                urlTongCuc: '',
                urlCuc: '',
                urlChiCuc: '',
                children: [
                    {
                        icon: 'htvbdh_tcdt_nhomquyen',
                        title: 'Kế hoạch lựa chọn nhà thầu',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_nhomquyen2',
                        title: 'Tổ chức triển khai lựa chọn nhà thầu',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_nhomquyen2',
                        title: 'Điều chỉnh kế hoạch lựa chọn nhà thầu',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                ]
            },
            {
                title: 'Gạo',
                icon: '',
                hasChild: true,
                url: '',
                urlTongCuc: '',
                urlCuc: '',
                urlChiCuc: '',
                children: [
                    {
                        icon: 'htvbdh_tcdt_nhomquyen',
                        title: 'Kế hoạch lựa chọn nhà thầu',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_nhomquyen2',
                        title: 'Tổ chức triển khai lựa chọn nhà thầu',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_nhomquyen2',
                        title: 'Điều chỉnh kế hoạch lựa chọn nhà thầu',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                ]
            },
            {
                title: 'Muối',
                icon: '',
                hasChild: true,
                url: '',
                urlTongCuc: '',
                urlCuc: '',
                urlChiCuc: '',
                children: [
                    {
                        icon: 'htvbdh_tcdt_nhomquyen',
                        title: 'Kế hoạch lựa chọn nhà thầu',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_nhomquyen2',
                        title: 'Tổ chức triển khai lựa chọn nhà thầu',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_nhomquyen2',
                        title: 'Điều chỉnh kế hoạch lựa chọn nhà thầu',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                ]
            },
            {
                title: 'Vật tư',
                icon: '',
                hasChild: true,
                url: '',
                urlTongCuc: '',
                urlCuc: '',
                urlChiCuc: '',
                children: [
                    {
                        icon: 'htvbdh_tcdt_nhomquyen',
                        title: 'Kế hoạch lựa chọn nhà thầu',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_nhomquyen2',
                        title: 'Tổ chức triển khai lựa chọn nhà thầu',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_nhomquyen2',
                        title: 'Điều chỉnh kế hoạch lựa chọn nhà thầu',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                ]
            },
        ]
    },
    {
        icon: 'htvbdh_tcdt_kynhay',
        title: 'Ký hợp đồng',
        url: `/hop-dong`,
        dropdown: 'hop-dong',
        idHover: 'hop-dong',
        hasTab: false,
        children: [
            {
                icon: 'htvbdh_tcdt_bienbangiaonhan',
                title: 'Hợp đồng thóc',
                hasChild: false,
                url: '/hop-dong/thoc/danh-sach',
                urlTongCuc: '',
                urlCuc: '',
                urlChiCuc: '',
            },
            {
                icon: 'htvbdh_tcdt_bienbangiaonhan',
                title: 'Hợp đồng gạo',
                hasChild: false,
                url: '/hop-dong/gao/danh-sach',
                urlTongCuc: '',
                urlCuc: '',
                urlChiCuc: '',
            },
            {
                icon: 'htvbdh_tcdt_bienbangiaonhan',
                title: 'Hợp đồng vật tư',
                hasChild: false,
                url: '/hop-dong/vat-tu/danh-sach',
                urlTongCuc: '',
                urlCuc: '',
                urlChiCuc: '',
            },
            {
                icon: 'htvbdh_tcdt_bienbangiaonhan',
                title: 'Hợp đồng muối',
                hasChild: false,
                url: '/hop-dong/muoi/danh-sach',
                urlTongCuc: '',
                urlCuc: '',
                urlChiCuc: '',
            },
            {
                icon: 'htvbdh_tcdt_phuluc',
                title: 'Phụ lục hợp đồng',
                hasChild: false,
                url: '/hop-dong/phu-luc',
                urlTongCuc: '',
                urlCuc: '',
                urlChiCuc: '',
            },
        ]
    },
    {
        icon: 'htvbdh_tcdt_baocao2',
        title: 'Báo cáo',
        url: `/bao-cao`,
        dropdown: 'bao-cao',
        idHover: 'bao-cao',
        hasTab: false,
        children: []
    },
];
