export const NOI_DUNG = [
    {
        id: 100,
        tenDm: "TỔNG NHU CẦU CHI NSNN",
        level: 0,
        idCha: 0,
    },
    {
        id: 110,
        tenDm: "Chi đầu tư phát triển",
        level: 1,
        idCha: 100,
    },
    {
        id: 111,
        tenDm: "Chi đầu tư các dự án",
        level: 2,
        idCha: 110,
    },
    {
        id: 112,
        tenDm: "Chi quốc phòng",
        level: 2,
        idCha: 110,
    },
    {
        id: 113,
        tenDm: "Chi an ninh và trật tự ATXH",
        level: 2,
        idCha: 110,
    },
    {
        id: 114,
        tenDm: "Chi đầu tư và hỗ trợ vốn cho DN cung cấp sản phẩm, dịch vụ công ích; các tổ chức kinh tế; các tổ chức tài chính; đầu tư vốn NN vào DN",
        level: 2,
        idCha: 110,
    },
    {
        id: 115,
        tenDm: "Chi đầu tư phát triển khác",
        level: 2,
        idCha: 110,
    },
    {
        id: 120,
        tenDm: "Chi thường xuyên*",
        level: 1,
        idCha: 100,
    },
    {
        id: 121,
        tenDm: "Chi quốc phòng",
        level: 2,
        idCha: 120,
    },
    {
        id: 122,
        tenDm: "Chi an ninh và trật tự ATXH",
        level: 2,
        idCha: 120,
    },
    {
        id: 200,
        tenDm: "CHI TỪ NGUỒN THU PHÍ ĐƯỢC ĐỂ LẠI CHO ĐƠN VỊ SỬ DỤNG THEO QUY ĐỊNH",
        level: 0,
        idCha: 0,
    },
    {
        id: 210,
        tenDm: "Chi sự nghiệp",
        level: 1,
        idCha: 200,
    },
    {
        id: 220,
        tenDm: "Chi quản lý hành chính",
        level: 1,
        idCha: 200,
    },
    {
        id: 300,
        tenDm: "NHU CẦU CHI CÒN LẠI, SAU KHI TRỪ ĐI SỐ CHI TỪ NGUỒN THU ĐỂ LẠI CHO ĐƠN VỊ SỬ DỤNG (A-B)",
        level: 0,
        idCha: 0,
    },
    {
        id: 310,
        tenDm: "Chi đầu tư phát triển",
        level: 1,
        idCha: 300,
    },
    {
        id: 311,
        tenDm: "Chi đầu tư các dự án",
        level: 2,
        idCha: 310,
    },
    {
        id: 312,
        tenDm: "Chi quốc phòng",
        level: 2,
        idCha: 310,
    },
    {
        id: 313,
        tenDm: "Chi an ninh và trật tự ATXH",
        level: 2,
        idCha: 310,
    },
    {
        id: 314,
        tenDm: "Chi đầu tư và hỗ trợ vốn cho DN cung cấp sản phẩm, dịch vụ công ích; các tổ chức kinh tế; các tổ chức tài chính; đầu tư vốn NN vào DN",
        level: 2,
        idCha: 310,
    },
    {
        id: 315,
        tenDm: "Chi đầu tư phát triển khác",
        level: 2,
        idCha: 310,
    },
    {
        id: 320,
        tenDm: "Chi thường xuyên*",
        level: 1,
        idCha: 300,
    },
    {
        id: 321,
        tenDm: "Chi quốc phòng",
        level: 2,
        idCha: 320,
    },
    {
        id: 322,
        tenDm: "Chi an ninh và trật tự ATXH",
        level: 2,
        idCha: 320,
    },
]