import { ChiTietMenu } from "src/app/models/ChiTietMenu";

export const BAN_HANG_MAIN_ROUTE = 'nhap';
export const BAN_HANG_ROUTE_LIST: Array<ChiTietMenu> = [
    {
        icon: 'htvbdh_tcdt_dauthau',
        title: 'Bán đấu giá',
        url: '',
        dropdown: 'dau-thau',
        idHover: 'dauthau',
        hasTab: true,
        children: [
            {
                icon: '',
                title: 'Thóc',
                hasChild: true,
                url: '',
                urlTongCuc: '',
                urlCuc: '',
                urlChiCuc: '',
                children: [
                    {
                        icon: 'htvbdh_tcdt_chitieukehoachnam',
                        title: 'Kế hoạch',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_tochucthuchien',
                        title: 'Tổ chức thực hiện',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_dieuchinhkehoachnam',
                        title: 'Điều chỉnh kế hoạch',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                ]
            },
            {
                icon: '',
                title: 'Gạo',
                hasChild: true,
                url: '',
                urlTongCuc: '',
                urlCuc: '',
                urlChiCuc: '',
                children: [
                    {
                        icon: 'htvbdh_tcdt_chitieukehoachnam',
                        title: 'Kế hoạch',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_tochucthuchien',
                        title: 'Tổ chức thực hiện',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_dieuchinhkehoachnam',
                        title: 'Điều chỉnh kế hoạch',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                ]
            },
            {
                icon: '',
                title: 'Muối',
                hasChild: true,
                url: '',
                urlTongCuc: '',
                urlCuc: '',
                urlChiCuc: '',
                children: [
                    {
                        icon: 'htvbdh_tcdt_chitieukehoachnam',
                        title: 'Kế hoạch',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_tochucthuchien',
                        title: 'Tổ chức thực hiện',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_dieuchinhkehoachnam',
                        title: 'Điều chỉnh kế hoạch',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                ]
            },
            {
                icon: '',
                title: 'Vật tư, thiết bị',
                hasChild: true,
                url: '',
                urlTongCuc: '',
                urlCuc: '',
                urlChiCuc: '',
                children: [
                    {
                        icon: 'htvbdh_tcdt_chitieukehoachnam',
                        title: 'Kế hoạch',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_tochucthuchien',
                        title: 'Tổ chức thực hiện',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_dieuchinhkehoachnam',
                        title: 'Điều chỉnh kế hoạch',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                ]
            },
        ]
    },
    {
        icon: 'htvbdh_tcdt_Thanhly',
        title: 'Bán trực tiếp rộng rãi',
        url: '',
        dropdown: 'dau-thau',
        idHover: 'dauthau',
        hasTab: true,
        children: [
            {
                icon: '',
                title: 'Thóc',
                hasChild: true,
                url: '',
                urlTongCuc: '',
                urlCuc: '',
                urlChiCuc: '',
                children: [
                    {
                        icon: 'htvbdh_tcdt_chitieukehoachnam',
                        title: 'Kế hoạch',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_tochucthuchien',
                        title: 'Tổ chức thực hiện',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_dieuchinhkehoachnam',
                        title: 'Điều chỉnh kế hoạch',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                ]
            },
            {
                icon: '',
                title: 'Gạo',
                hasChild: true,
                url: '',
                urlTongCuc: '',
                urlCuc: '',
                urlChiCuc: '',
                children: [
                    {
                        icon: 'htvbdh_tcdt_chitieukehoachnam',
                        title: 'Kế hoạch',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_tochucthuchien',
                        title: 'Tổ chức thực hiện',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_dieuchinhkehoachnam',
                        title: 'Điều chỉnh kế hoạch',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                ]
            },
            {
                icon: '',
                title: 'Muối',
                hasChild: true,
                url: '',
                urlTongCuc: '',
                urlCuc: '',
                urlChiCuc: '',
                children: [
                    {
                        icon: 'htvbdh_tcdt_chitieukehoachnam',
                        title: 'Kế hoạch',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_tochucthuchien',
                        title: 'Tổ chức thực hiện',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_dieuchinhkehoachnam',
                        title: 'Điều chỉnh kế hoạch',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                ]
            },
            {
                icon: '',
                title: 'Vật tư, thiết bị',
                hasChild: true,
                url: '',
                urlTongCuc: '',
                urlCuc: '',
                urlChiCuc: '',
                children: [
                    {
                        icon: 'htvbdh_tcdt_chitieukehoachnam',
                        title: 'Kế hoạch',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_tochucthuchien',
                        title: 'Tổ chức thực hiện',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                    {
                        icon: 'htvbdh_tcdt_dieuchinhkehoachnam',
                        title: 'Điều chỉnh kế hoạch',
                        url: '',
                        urlTongCuc: '',
                        urlCuc: '',
                        urlChiCuc: '',
                    },
                ]
            },
        ]
    },
    {
        icon: 'htvbdh_tcdt_baocao2',
        title: 'Báo cáo',
        url: '',
        dropdown: 'bao-cao',
        idHover: 'bao-cao',
        hasTab: false,
    },
];
