export const LINH_VUC = [
  {
    id: 1000,
    tenDm: "Kinh phí thực hiện tự chủ",
    idCha: 0,
    level: 0,
  },
  {
    id: 1100,
    tenDm: "Quỹ lương",
    idCha: 1000,
    level: 1,
  },
  {
    id: 1200,
    tenDm: "Chi quản lý hành chính theo định mức",
    idCha: 1000,
    level: 2,
  },
  {
    id: 1300,
    tenDm: "Kinh phí thực hiện điều chỉnh tiền lương theo nghị định số 38/2018NĐ-CP",
    idCha: 1000,
    level: 1,
  },
  {
    id: 1400,
    tenDm: "Chi lương phụ cấp và các khoản đóng góp theo lương của các LĐHĐ theo NĐ 68",
    idCha: 1000,
    level: 1,
  },
  {
    id: 1500,
    tenDm: "Chi mua sắm tài sản",
    idCha: 1000,
    level: 1,
  },
  {
    id: 1600,
    tenDm: "Chi sửa chữa tài sản",
    idCha: 1000,
    level: 1,
  },
  {
    id: 1700,
    tenDm: "Chi thường xuyên theo định mức",
    idCha: 1000,
    level: 1,
  },
  //=============
  {
    id: 2000,
    tenDm: "Kinh phí không thực hiện tự chủ",
    idCha: 0,
    level: 0,
  },
  {
    id: 2100,
    tenDm: "Chi ứng dụng công nghệ thông tin",
    idCha: 2000,
    level: 1,
  },
  {
    id: 2200,
    tenDm: "Thực hiện chính sách tinh giản biên chế",
    idCha: 2000,
    level: 1,
  },
  {
    id: 2300,
    tenDm: "Chi cải tạo sửa chữa lớn kho DTQG",
    idCha: 2000,
    level: 1,
  },
  {
    id: 2400,
    tenDm: "Phí bảo quản hàng DTQG",
    idCha: 2000,
    level: 1,
  },
  {
    id: 2500,
    tenDm: "Phí nhập xuất hàng DTQG",
    idCha: 2000,
    level: 1,
  },
  {
    id: 2600,
    tenDm: "Phí xuất hàng DTQG viện trợ cứu trợ",
    idCha: 2000,
    level: 1,
  },
  {
    id: 2700,
    tenDm: "Chi khác",
    idCha: 2000,
    level: 1,
  },
  {
    id: 2800,
    tenDm: "Chi đề tài nghiên cứu khoa học",
    idCha: 2000,
    level: 1,
  },
  {
    id: 2900,
    tenDm: "Chi đào tạo bồi dưỡng CBCC",
    idCha: 2000,
    level: 1,
  },
  {
    id: 21000,
    tenDm: "Chi hoạt động đảm bảo xã hội",
    idCha: 2000,
    level: 1,
  },
]
