export const NHAP_MAIN_ROUTE = 'quan-tri-danh-muc';
export const NHAP_ROUTE_LIST = [
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Danh mục dùng chung',
    url: `/${NHAP_MAIN_ROUTE}/danh-muc-dung-chung`,
    dropdown: 'ql-danh-muc-dung-chung',
    idHover: 'danh-muc-dung-chung',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Danh mục đơn vị',
    url: `/${NHAP_MAIN_ROUTE}/danh-muc-don-vi`,
    dropdown: 'danh-muc-don-vi',
    idHover: 'danh-muc-don-vi',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Danh mục hàng DTQG',
    url: `/${NHAP_MAIN_ROUTE}/danh-muc-hang-hoa`,
    dropdown: 'danh-muc-hang-hoa',
    idHover: 'danh-muc-hang-hoa',
  },
  // {
  //   icon: 'htvbdh_tcdt_icon-common',
  //   title: 'Danh mục hàng DTQG',
  //   url: `/${NHAP_MAIN_ROUTE}/danh-muc-hang-dtqg`,
  //   dropdown: 'danh-muc-hang-dtqg',
  //   idHover: 'danh-muc-hang-dtqg',
  // },
  // {
  //   icon: 'htvbdh_tcdt_icon-common',
  //   title: 'Danh mục vật tư theo hàng',
  //   url: `/${NHAP_MAIN_ROUTE}/danh-muc-vat-tu-theo-hang`,
  //   dropdown: 'danh-muc-vat-tu-theo-hang',
  //   idHover: 'danh-muc-vat-tu-theo-hang',
  // },
  // {
  //   icon: 'htvbdh_tcdt_icon-common',
  //   title: 'Danh mục địa điểm kho theo chi cục',
  //   url: `/${NHAP_MAIN_ROUTE}/danh-muc-dia-diem-kho-theo-chi-cuc`,
  //   dropdown: 'danh-muc-dia-diem-kho-theo-chi-cuc',
  //   idHover: 'danh-muc-dia-diem-kho-theo-chi-cuc',
  // },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'DM định mức phí nhập, xuất, bảo quản',
    url: `/${NHAP_MAIN_ROUTE}/danh-muc-dinh-muc-phi`,
    dropdown: 'danh-muc-dinh-muc-phi',
    idHover: 'danh-muc-dinh-muc-phi',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'DM công cụ, dụng cụ',
    url: `/${NHAP_MAIN_ROUTE}/danh-muc-cong-cu-dung-cu`,
    dropdown: 'danh-muc-cong-cu-dung-cu',
    idHover: 'danh-muc-cong-cu-dung-cu',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Danh mục tài sản',
    url: `/${NHAP_MAIN_ROUTE}/danh-muc-tai-san`,
    dropdown: 'danh-muc-tai-san',
    idHover: 'danh-muc-tai-san',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'DM đơn vị liên quan',
    url: `/${NHAP_MAIN_ROUTE}/danh-muc-dvi-lien-quan`,
    dropdown: 'danh-muc-dvi-lien-quan',
    idHover: 'danh-muc-dvi-lien-quan',
  },
  {
    icon: 'htvbdh_tcdt_icon-common',
    title: 'Danh mục thủ kho',
    url: `/${NHAP_MAIN_ROUTE}/danh-muc-thu-kho`,
    dropdown: 'danh-muc-thu-kho',
    idHover: 'danh-muc-thu-kho',
  },
];
