export const PHU_LUC = [
    {
        id: 'pl01',
        tenDm: 'Tổng hợp điều chỉnh dự toán chi NSNN đợt I/',
        tenPl: 'Phụ lục I',
        status: false,
    },
    {
        id: 'pl02',
        tenDm: 'Chi tiết dự toán chi mua sắm tài sản cố định ',
        tenPl: 'Phụ lục II',
        status: false,
    },
    {
        id: 'pl03',
        tenDm: 'Chi tiết chi quản lý hành chính ',
        tenPl: 'Phụ lục III',
        status: false,
    },
    {
        id: 'pl04',
        tenDm: 'Chi tiết dự toán chi ứng dụng công nghệ thông tin ',
        tenPl: 'Phụ lục IV',
        status: false,
    },
    {
        id: 'pl05',
        tenDm: 'Dự toán phí nhập hàng DTQG ',
        tenPl: 'Phụ lục V',
        status: false,
    },
    {
        id: 'pl06',
        tenDm: 'Dự toán phí xuất hàng DTQG ',
        tenPl: 'Phụ lục VI',
        status: false,
    },
    {
        id: 'pl07',
        tenDm: 'Dự toán phí viện trợ, cứu trợ ',
        tenPl: 'Phụ lục VII',
        status: false,
    },
    {
        id: 'pl08',
        tenDm: 'Dự toán bảo quản hàng DTQG ',
        tenPl: 'Phụ lục VIII',
        status: false,
    },
    {
        id: 'pl09',
        tenDm: 'Bảng lương ',
        tenPl: 'Phụ lục IX',
        status: false,
    },
    {
        id: 'pl10',
        tenDm: 'Bảng tổng hợp tình hình thực hiện, điều chỉnh dự toán cải tạo sửa chữa lớn kho DTQG ',
        tenPl: 'Phụ lục X',
        status: false,
    },
    {
        id: 'pl11',
        tenDm: 'Chi đào tạo, bồi dưỡng cán bộ, công chức nhà nước',
        tenPl: 'Phụ lục XI',
        status: false,
    },
    {
        id: 'pl12',
        tenDm: 'Chi sự nghiệp khoa học công nghệ ',
        tenPl: 'Phụ lục XII',
        status: false,
    },
    {
        id: 'pl13',
        tenDm: 'Chi hoạt động bảo đảm xã hội',
        tenPl: 'Phụ lục XIII',
        status: false,
    },
];

export const PHU_LUC_TH = [
    {
        id: 'pl01TH',
        tenDm: 'Tổng hợp điều chỉnh dự toán chi NSNN đợt I/',
        tenPl: 'Phụ lục I',
        status: false,
    },
    {
        id: 'pl02',
        tenDm: 'Chi tiết dự toán chi mua sắm tài sản cố định ',
        tenPl: 'Phụ lục II',
        status: false,
    },
    {
        id: 'pl03',
        tenDm: 'Chi tiết chi quản lý hành chính ',
        tenPl: 'Phụ lục III',
        status: false,
    },
    {
        id: 'pl04',
        tenDm: 'Chi tiết dự toán chi ứng dụng công nghệ thông tin ',
        tenPl: 'Phụ lục IV',
        status: false,
    },
    {
        id: 'pl05',
        tenDm: 'Dự toán phí nhập hàng DTQG ',
        tenPl: 'Phụ lục V',
        status: false,
    },
    {
        id: 'pl06',
        tenDm: 'Dự toán phí xuất hàng DTQG ',
        tenPl: 'Phụ lục VI',
        status: false,
    },
    {
        id: 'pl07',
        tenDm: 'Dự toán phí viện trợ, cứu trợ ',
        tenPl: 'Phụ lục VII',
        status: false,
    },
    {
        id: 'pl08',
        tenDm: 'Dự toán bảo quản hàng DTQG ',
        tenPl: 'Phụ lục VIII',
        status: false,
    },
    {
        id: 'pl09',
        tenDm: 'Bảng lương ',
        tenPl: 'Phụ lục IX',
        status: false,
    },
    {
        id: 'pl10',
        tenDm: 'Bảng tổng hợp tình hình thực hiện, điều chỉnh dự toán cải tạo sửa chữa lớn kho DTQG ',
        tenPl: 'Phụ lục X',
        status: false,
    },
    {
        id: 'pl11',
        tenDm: 'Chi đào tạo, bồi dưỡng cán bộ, công chức nhà nước ',
        tenPl: 'Phụ lục XI',
        status: false,
    },
    {
        id: 'pl12',
        tenDm: 'Chi sự nghiệp khoa học công nghệ ',
        tenPl: 'Phụ lục XII',
        status: false,
    },
    {
        id: 'pl13',
        tenDm: 'Chi hoạt động bảo đảm xã hội',
        tenPl: 'Phụ lục XIII',
        status: false,
    },
];